# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percent_votes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
